jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      # 1. PASSO DE UPLOAD (Este é o que gera o artefato que estava faltando)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # O caminho '.' indica que os arquivos do seu portfólio estão na raiz do repositório
          path: '.'

      # 2. PASSO DE DEPLOY (Este é o que envia o artefato para o ar)
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
